#!/bin/bash
: '
    ** Copyright (c) 2017, Autonomous Networks Research Group. All rights reserved.
    **     contributor: Quynh Nguyen, Bhaskar Krishnamachari
    **     Read license file in main directory for more details
'

root_folder=$PWD
my_ip=$1
file_name='_test_'

declare -a file_size=(1 10 100 1000 10000);

for i in "${file_size[@]}"
do
    random_file=$my_ip$file_name$i"K"
    file_path=$root_folder/generated_test/$random_file

    echo 'Create file'
    dd if=/dev/urandom of=$file_path bs=1K count=$i #KBytes
done
