#!/bin/bash

: '
    ** Copyright (c) 2017, Autonomous Networks Research Group. All rights reserved.
    **     contributor: Quynh Nguyen, Bhaskar Krishnamachari
    **     Read license file in main directory for more details
'

for account in `awk -F ',' 'NR >=2 {print $2}' central_input/nodes.txt `; do
    echo $account
    remote_folder='networkprofiling/scheduling/'
    source_file=/root/networkprofiling/scheduling/$account/scheduling.txt
    destination_file=root@$account:~/$remote_folder
    sshpass -p 'apac20!7' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 5100 $source_file $destination_file
    source_file=/root/networkprofiling/central.txt
    sshpass -p 'apac20!7' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 5100 $source_file root@$account:~/networkprofiling
done